apiVersion: v1
kind: Pod
metadata:
  name: kaniko-boilerplate
spec:
  containers:
    - name: kaniko
      image: registry.aliyuncs.com/kaniko-project/executor:latest
      args:
        - "--force"
        - "--dockerfile=/workspace/Dockerfile"
        - "--context=dir:///workspace"
        - "--destination=harbor.leryn.top/library/python-docker:v1.0"
      volumeMounts:
        - name: kaniko-registry
          mountPath: /kaniko/.docker
        - name: workspace-storage
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-registry
      secret:
        secretName: kaniko-registry
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: workspace-storage
      hostPath:
        path: </path/to/project>
